namespace DiskEye.Forms;

/// <summary>
/// V0.9.15: 双语字典（中文默认 / English）。
/// 编译期 C# 常量，零加载失败面。加新文案：Zh/En 各加一条同 key，代码里 L.T("key")。
/// </summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "DiskEye — 硬盘监控",
        ["status.precise"] = "● 精确归因（ETW） · 今日真实写入 {0}",
        ["status.degraded"] = "○ 降级（启发式） · 今日写入字节暂停 · {0}（截至降级前）",
        ["search.hint"] = "搜索（跨所有 tab 过滤）：",
        ["search.placeholder"] = "输入进程名/路径/PID 过滤（清空显示全部）",
        ["search.clear"] = "清空",

        ["tab.offender"] = "凶手指控榜",
        ["tab.folders"] = "文件夹重灾区",
        ["tab.stream"] = "事件流",
        ["tab.chart"] = "今日趋势",
        ["tab.tree"] = "进程树",
        ["tab.clean"] = "垃圾清理",
        ["tab.tools"] = "工具",
        ["tab.settings"] = "设置",

        ["col.process"] = "进程名",
        ["col.exepath"] = "可执行路径",
        ["col.topfolder"] = "主要写入目录（往哪倒垃圾）",
        ["col.events"] = "事件数",
        ["col.writebytes"] = "写入字节",
        ["col.lastactivity"] = "最近活动",
        ["col.folder"] = "文件夹",
        ["col.time"] = "时间",
        ["col.drive"] = "盘符",
        ["col.type"] = "事件",
        ["col.file"] = "文件",
        ["col.filesize"] = "文件大小",
        ["col.pid"] = "PID",
        ["col.ppid"] = "父 PID",
        ["col.pname"] = "父进程",

        ["hint.offender"] = "今日哪个进程写的文件最多？点行看明细",
        ["hint.folders"] = "今天硬盘被写最多的是哪个目录？双击行 = 用资源管理器打开",
        ["hint.tree"] = "今日活跃进程 + 父进程信息（按真实写入字节倒序）",
        ["hint.chart"] = "今日 24 小时写入字节柱状图（鼠标移到柱子上看具体值）",

        ["row.exited"] = "（已退出，未抓到 exe 路径）",
        ["tray.today"] = "今日写入：{0}（ETW 实测）",
        ["tray.today.paused"] = "今日写入：{0}（降级中，字节暂停）",
        ["tray.attrib.precise"] = "归因：● 精确（ETW FileObject）",
        ["tray.attrib.degraded"] = "归因：○ 降级（启发式）",
        ["tray.show"] = "打开主界面(&O)",
        ["tray.topfolders"] = "今日最狠文件夹(&F)...",
        ["tray.drives"] = "监控盘符(&D)",
        ["tray.settings"] = "设置(&S)...",
        ["tray.exit"] = "退出(&E)",
        ["tray.tooltip"] = "DiskEye — 硬盘监控（双击打开主界面，右键菜单）",

        ["clean.scan"] = "扫描",
        ["clean.run"] = "清理选中项",
        ["clean.hint"] = "只清理白名单目录（用户 Temp / 浏览器缓存 / 缩略图）。Temp 只删 24 小时前的旧文件；被占用的自动跳过。绝不碰其他目录。",
        ["clean.scanning"] = "扫描中…",
        ["clean.found"] = "识别到 {0} 项可清理",
        ["clean.none"] = "很干净，没有可清理项",
        ["clean.running"] = "清理中…",
        ["clean.done"] = "✅ 已释放 {0}（跳过被占用 {1} 个文件）",
        ["clean.col.pick"] = "清理",
        ["clean.col.item"] = "项目",
        ["clean.col.path"] = "路径",
        ["clean.col.files"] = "文件数",
        ["clean.col.freeable"] = "可释放",
        ["clean.target.temp"] = "用户临时目录 (%TEMP%)",
        ["clean.target.diskmon"] = "{0} 的 DiskEye 监控临时残留",
        ["clean.target.browser"] = "{0} 缓存（{1}\\{2}）",
        ["clean.target.thumb"] = "缩略图缓存（thumbcache）",

        ["settings.autostart"] = "Windows 登录后自动后台运行",
        ["settings.autostart.label"] = "开机自启动：",
        ["settings.save"] = "保存设置",
        ["settings.language"] = "语言 / Language",
        ["settings.drives"] = "监控盘符：",
        ["settings.drive.item"] = "{0}: 盘",
        ["settings.include"] = "白名单前缀：\n（空=全部监控；填了=只监控这些路径）",
        ["settings.ignore"] = "黑名单前缀：\n（命中即忽略，每行一个路径）",
        ["settings.surge"] = "异常增长弹窗阈值",
        ["settings.surge.process"] = "进程阈值 (MB)：",
        ["settings.surge.folder"] = "文件夹阈值 (MB)：",
        ["settings.surge.window"] = "检测窗口 (秒)：",
        ["settings.surge.cooldown"] = "冷却时间 (分钟)：",
        ["settings.hint"] = "设置修改后立即生效。归档策略：>30 天的事件自动移到 events_archive 表（数据不丢）。\nV3 白/黑名单：填路径前缀。V5.1 阈值：进程/文件夹在窗口期内超过阈值就弹通知。",

        ["tools.export"] = "数据导出",
        ["tools.export.all"] = "导出全部事件到 CSV…",
        ["tools.export.today"] = "导出今日事件",
        ["tools.export.hint"] = "CSV 用 UTF-8 + BOM 编码，可直接用 Excel 打开。",
        ["tools.data"] = "数据管理",
        ["tools.archive"] = "立即归档（>30 天的事件移到 archive 表）",
        ["tools.stats"] = "数据统计",
        ["tools.stats.format"] = "数据库大小: {0}    事件总数: {1}    监控时长: {2} 天    最早: {3}    最近: {4}",
        ["tools.stats.fail"] = "统计失败: {0}",

        ["detail.title"] = "{0} 详情",
        ["detail.header"] = "进程 {0} — 今日事件明细（共 {1} 条）",
        ["detail.header.pid"] = "进程 {0} (PID {1}) — 今日事件明细（共 {2} 条）",
        ["detail.truncated"] = "... 仅显示前 200 条，共 {0} 条",

        ["chart.title"] = "今日写入趋势（峰值: {0}）",

        ["ctxmenu.open"] = "用资源管理器打开",
        ["ctxmenu.copy"] = "复制路径",

        ["msg.open.fail"] = "打开失败: {0}",
        ["msg.exported"] = "已导出 {0} 条事件到：\n{1}",
        ["msg.export.fail"] = "导出失败: {0}",
        ["msg.archived"] = "已归档 {0} 条事件",
        ["msg.archive.fail"] = "归档失败: {0}",
        ["msg.settings.saved"] = "设置已保存",
        ["msg.settings.saved.lang"] = "设置已保存。语言已切换。",

        ["surge.alert.process"] = "进程突增",
        ["surge.alert.folder"] = "文件夹突增",
        ["surge.alert.msg"] = "{0} 在 {1:F0}s 内写了 {2} ({3} 个文件)",

        ["error.refresh"] = "DiskEye — ⚠ 数据刷新失败（详见日志）",
        ["error.query"] = "DiskEye — ⚠ 数据查询失败（详见日志）",

        ["firstrun.title"] = "DiskEye — 首次运行",
        ["firstrun.hint"] = "DiskEye 会在后台监控你选定的盘符下文件变化。\n想知道哪个进程突然写了几个 GB？先选要监控的盘符。",
        ["firstrun.autostart"] = "开机自动启动（后台运行）",
        ["firstrun.start"] = "开始监控 →",
        ["firstrun.select.drive"] = "至少选一个盘符",

        ["popup.title"] = "DiskEye — 今日最狠文件夹（Top 10）",
        ["popup.empty"] = "（今天还没有文件变化事件）",
        ["popup.header"] = "排名    大小       事件数   文件夹",

        ["dlg.csv.filter"] = "CSV 文件 (*.csv)|*.csv",

        ["about.menu"] = "关于(&A)...",
        ["about.text"] = "DiskEye v{0}\n硬盘写入监控 · 绿色便携单文件\nETW 精确归因 · SQLite 本地存储",
    };

    public static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "DiskEye — Disk Monitor",
        ["status.precise"] = "● Precise attribution (ETW) · Real writes today {0}",
        ["status.degraded"] = "○ Degraded (heuristic) · Byte metering paused · {0} (before degradation)",
        ["search.hint"] = "Search (filters all tabs):",
        ["search.placeholder"] = "Type process name / path / PID to filter (empty = show all)",
        ["search.clear"] = "Clear",

        ["tab.offender"] = "Top Offenders",
        ["tab.folders"] = "Hot Folders",
        ["tab.stream"] = "Event Stream",
        ["tab.chart"] = "Today Trend",
        ["tab.tree"] = "Process Tree",
        ["tab.clean"] = "Junk Cleaner",
        ["tab.tools"] = "Tools",
        ["tab.settings"] = "Settings",

        ["col.process"] = "Process",
        ["col.exepath"] = "Executable Path",
        ["col.topfolder"] = "Main Write Folder",
        ["col.events"] = "Events",
        ["col.writebytes"] = "Written Bytes",
        ["col.lastactivity"] = "Last Activity",
        ["col.folder"] = "Folder",
        ["col.time"] = "Time",
        ["col.drive"] = "Drive",
        ["col.type"] = "Type",
        ["col.file"] = "File",
        ["col.filesize"] = "File Size",
        ["col.pid"] = "PID",
        ["col.ppid"] = "Parent PID",
        ["col.pname"] = "Parent Process",

        ["hint.offender"] = "Which process wrote the most today? Click a row for details",
        ["hint.folders"] = "Which directory got the most writes today? Double-click to open in Explorer",
        ["hint.tree"] = "Active processes today + parent info (sorted by real written bytes)",
        ["hint.chart"] = "Today's 24-hour write bar chart (hover a bar for exact value)",

        ["row.exited"] = "(exited, exe path not captured)",
        ["tray.today"] = "Today written: {0} (ETW measured)",
        ["tray.today.paused"] = "Today written: {0} (paused)",
        ["tray.attrib.precise"] = "Attribution: ● Precise (ETW FileObject)",
        ["tray.attrib.degraded"] = "Attribution: ○ Degraded (heuristic)",
        ["tray.show"] = "Open Main Window (&O)",
        ["tray.topfolders"] = "Top Folders Today (&F)...",
        ["tray.drives"] = "Monitored Drives (&D)",
        ["tray.settings"] = "Settings (&S)...",
        ["tray.exit"] = "Exit (&E)",
        ["tray.tooltip"] = "DiskEye — Disk Monitor (double-click main window, right-click menu)",

        ["clean.scan"] = "Scan",
        ["clean.run"] = "Clean Selected",
        ["clean.hint"] = "Only whitelisted locations (user Temp / browser caches / thumbnails). Temp: files older than 24h only; in-use files skipped. Never touches anything else.",
        ["clean.scanning"] = "Scanning…",
        ["clean.found"] = "{0} item(s) can be cleaned",
        ["clean.none"] = "All clean, nothing to clean",
        ["clean.running"] = "Cleaning…",
        ["clean.done"] = "✅ Freed {0} (skipped {1} in-use files)",
        ["clean.col.pick"] = "Clean",
        ["clean.col.item"] = "Item",
        ["clean.col.path"] = "Path",
        ["clean.col.files"] = "Files",
        ["clean.col.freeable"] = "Freeable",
        ["clean.target.temp"] = "User Temp Directory (%TEMP%)",
        ["clean.target.diskmon"] = "{0}'s DiskEye monitoring temp residue",
        ["clean.target.browser"] = "{0} Cache ({1}\\{2})",
        ["clean.target.thumb"] = "Thumbnail Cache (thumbcache)",

        ["settings.autostart"] = "Run silently in background on Windows login",
        ["settings.autostart.label"] = "Auto-start:",
        ["settings.save"] = "Save Settings",
        ["settings.language"] = "Language / 语言",
        ["settings.drives"] = "Monitored drives:",
        ["settings.drive.item"] = "{0}: drive",
        ["settings.include"] = "Include prefixes:\n(empty = monitor all; fill = monitor only these)",
        ["settings.ignore"] = "Ignore prefixes:\n(one path per line, matched = skip)",
        ["settings.surge"] = "Surge Alert Thresholds",
        ["settings.surge.process"] = "Process threshold (MB):",
        ["settings.surge.folder"] = "Folder threshold (MB):",
        ["settings.surge.window"] = "Detection window (sec):",
        ["settings.surge.cooldown"] = "Cooldown (min):",
        ["settings.hint"] = "Settings take effect immediately. Archive: events >30 days old moved to events_archive (data preserved).\nV3 include/ignore: path prefixes. V5.1 surge: alert when process/folder exceeds threshold within window.",

        ["tools.export"] = "Data Export",
        ["tools.export.all"] = "Export All Events to CSV…",
        ["tools.export.today"] = "Export Today's Events",
        ["tools.export.hint"] = "CSV uses UTF-8 + BOM encoding, opens directly in Excel.",
        ["tools.data"] = "Data Management",
        ["tools.archive"] = "Archive Now (>30 day events → archive table)",
        ["tools.stats"] = "Statistics",
        ["tools.stats.format"] = "DB size: {0}    Total events: {1}    Monitoring: {2} days    First: {3}    Last: {4}",
        ["tools.stats.fail"] = "Stats failed: {0}",

        ["detail.title"] = "{0} Details",
        ["detail.header"] = "Process {0} — Today's events ({1} total)",
        ["detail.header.pid"] = "Process {0} (PID {1}) — Today's events ({2} total)",
        ["detail.truncated"] = "... showing first 200 of {0} total",

        ["chart.title"] = "Today's Write Trend (peak: {0})",

        ["ctxmenu.open"] = "Open in Explorer",
        ["ctxmenu.copy"] = "Copy Path",

        ["msg.open.fail"] = "Open failed: {0}",
        ["msg.exported"] = "Exported {0} events to:\n{1}",
        ["msg.export.fail"] = "Export failed: {0}",
        ["msg.archived"] = "Archived {0} events",
        ["msg.archive.fail"] = "Archive failed: {0}",
        ["msg.settings.saved"] = "Settings saved",
        ["msg.settings.saved.lang"] = "Settings saved. Language switched.",

        ["surge.alert.process"] = "Process Surge",
        ["surge.alert.folder"] = "Folder Surge",
        ["surge.alert.msg"] = "{0} wrote {2} in {1:F0}s ({3} files)",

        ["error.refresh"] = "DiskEye — ⚠ Data refresh failed (see log)",
        ["error.query"] = "DiskEye — ⚠ Data query failed (see log)",

        ["firstrun.title"] = "DiskEye — First Run",
        ["firstrun.hint"] = "DiskEye monitors file changes on selected drives in the background.\nWant to know which process suddenly wrote several GB? Select drives to monitor first.",
        ["firstrun.autostart"] = "Auto-start on login (background)",
        ["firstrun.start"] = "Start Monitoring →",
        ["firstrun.select.drive"] = "Select at least one drive",

        ["popup.title"] = "DiskEye — Top Folders Today (Top 10)",
        ["popup.empty"] = "(No file events today)",
        ["popup.header"] = "Rank    Size       Events   Folder",

        ["dlg.csv.filter"] = "CSV Files (*.csv)|*.csv",

        ["about.menu"] = "About(&A)...",
        ["about.text"] = "DiskEye v{0}\nDisk Write Monitor · Portable Single-File\nETW Precise Attribution · SQLite Local Storage",
    };
}
